external-dns:
  fullnameOverride: "external-dns"
  interval: 30m
  policy: sync
  provider: aws
  registry: txt
  triggerLoopOnEvent: true

  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      cpu: 200m
      memory: 128Mi