{{- $prefix := printf "%s-%s-%s" (index .Values "infra-services" "region_short") (index .Values "infra-services" "environment") (index .Values "infra-services" "project_name") }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: devlake-encryption-secret
  namespace: devlake
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: secretstore-aws
    kind: ClusterSecretStore
  target:
    name: devlake-encryption-secret
    creationPolicy: Owner
  data:
    - secretKey: ENCRYPTION_SECRET
      remoteRef:
        key: {{ $prefix }}-devlake-encryption-secret