devlake:
  lake:
    encryptionSecret:
      secret: "YXVAQNJDVMEZQUREXCSDVPTGLJDGHFBSMLWKIOGGWXHYJPLJHCTTVBWDBILVIMRNICUFZTYPJEEDEEGIHITRCSFBJETOKKJHMULXJFMUXADRDHKKBMLPGUDUMYLUSKCG"
      autoCreateSecret: true
  grafana:
    enabled: false