devlake:
  lake:
    encryptionSecret:
      secret: "YXVAQNJDVMEZQUREXCSDVPTGLJDGHFBSMLWKIOGGWXHYJPLJHCTTVBWDBILVIMRNICUFZTYPJEEDEEGIHITRCSFBJETOKKJHMULXJFMUXADRDHKKBMLPGUDUMYLUSKCG"
      autoCreateSecret: true
  grafana:
    enabled: false
    external:
      url: "http://grafana.monitoring.svc.cluster.local"