apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: keycloak-pull-secret
  labels:
    app.kubernetes.io/name: keycloak
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: secretstore-vault
    kind: ClusterSecretStore
  target:
    name: keycloak-pull-secret
    creationPolicy: Owner
    template:
      type: kubernetes.io/dockerconfigjson
      data:
        .dockerconfigjson: |
          {"auths":{"registry.phoenix.net-digital.com":{"username":"{{ `{{ .username }}` }}","password":"{{ `{{ .token }}` }}","auth":"{{ `{{ printf "%s:%s" .username .token | b64enc }}` }}"}}}
  data:
    - secretKey: username
      remoteRef:
        key: common/image_registry_pull_secret
        property: username
    - secretKey: token
      remoteRef:
        key: common/image_registry_pull_secret
        property: password