apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: trivy-alerts
  namespace: monitoring
  labels:
    role: security-rules
spec:
  groups:
  - name: vulnerability-alerts
    rules:
    - alert: HighOrCriticalSeverityVulnerability
      labels:
        severity: security
      expr: >
        sum by (namespace, resource_kind, resource_name, config_audit_title, severity, config_audit_id) (
          trivy_configaudits_info{config_audit_success="false", severity=~"High|Critical"}
          unless
          (
            trivy_configaudits_info{severity="High", resource_name=~"kube-prometheus-stack-prometheus-node-exporter|.*chirpstack-lwn-simulator.*|azure-sdp-dev|storage-ext-service|azure-sdp|cc-biz-internal-rabbitmq-cluster-server|pgstats-dump|cc-biz-external-rabbitmq-cluster-server|.*chirpstack-e2e-test-simulator.*|landing-page"}
            or
            trivy_configaudits_info{severity="High", namespace=~"debug|kube-system|thingsboard|falco|dependency-track|trivy-operator|azureserviceoperator-system"}
          ) > 0)
      annotations:
        summary: "High or Critical severity vulnerability detected in {{ $labels.namespace }}/{{ $labels.resource_name }}"
        description: |
          High severity configuration vulnerability detected! | Resource Type: {{ $labels.resource_kind }} | Resource Name: {{ $labels.resource_name }} | Namespace: {{ $labels.namespace }} | Severity: {{ $labels.severity }}
    - alert: ContainerVulnerabilityDetected
      expr: |
        sum by (namespace, container_name, resource_name, image_repository, image_tag, vuln_id, severity) (
          trivy_vulnerability_id{severity=~"High|Critical"} > 0
        )
      for: 0m
      labels:
        severity: security
      annotations:
        summary: "CVE Detected: {{ $labels.vuln_id }} in {{ $labels.image_repository }}"
        description: |
          A vulnerability has been detected in the running container image. |  **CVE ID:** {{ $labels.vuln_id }} | **Severity:** {{ $labels.severity }} | **Repository:** {{ $labels.image_repository }} | **Tag:** {{ $labels.image_tag }} | **Affected Resource:** {{ $labels.resource_name }} | **Namespace:** {{ $labels.namespace }}
        runbook_url: "https://avd.aquasec.com/nvd/{{ $labels.vuln_id }}"
    - alert: InfraMisconfigurationDetected
      expr: |
        sum by (namespace, resource_kind, resource_name, infra_assessment_title, severity) (
          trivy_infraassessments_info{infra_assessment_success="false", severity=~"High|Critical"} > 0
        )
      for: 10m
      labels:
        severity: "{{ $labels.severity }}"
        security_domain: infrastructure
      annotations:
        summary: "Infra Issue: {{ $labels.infra_assessment_title }}"
        description: |
          Infrastructure-level security check failed. | **Check:** {{ $labels.infra_assessment_title }} | **Resource:** {{ $labels.resource_kind }}/{{ $labels.resource_name }} | **Namespace:** {{ $labels.namespace }}
    - alert: RiskyRBACPolicyDetected
      expr: |
        sum by (namespace, resource_kind, resource_name, rbac_assessment_title, severity, rbac_assessment_id) (
          trivy_rbacassessments_info{rbac_assessment_success="false", severity=~"High|Critical"} > 0
        )
      for: 15m
      labels:
        severity: "{{ $labels.severity }}"
        security_domain: rbac
      annotations:
        summary: "Insecure RBAC: {{ $labels.rbac_assessment_title }}"
        description: |
          A Kubernetes RBAC resource is over-privileged. | **Issue:** {{ $labels.rbac_assessment_title }} ({{ $labels.rbac_assessment_id }}) | **Resource:** {{ $labels.resource_kind }}/{{ $labels.resource_name }} | **Severity:** {{ $labels.severity }}
    - alert: ExposedSecretDetected
      expr: |
        sum by (namespace, resource_kind, resource_name, secret_category, secret_target, severity) (
          trivy_exposedsecrets_info{severity=~"High|Critical"} > 0
        )
      for: 5m
      labels:
        severity: "{{ $labels.severity }}"
        security_domain: secrets
      annotations:
        summary: "Secret Leak: {{ $labels.secret_category }} in {{ $labels.resource_name }}"
        description: |
          A potential secret leak was detected.| * **Category:** {{ $labels.secret_category }} | **Target File:** {{ $labels.secret_target }} | **Resource:** {{ $labels.resource_kind }}/{{ $labels.resource_name }} | **Namespace:** {{ $labels.namespace }}
