apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: qdrant-env-secret
  labels:
    app: {{ .Release.Name }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: {{ .Values.externalSecrets.secretStore }}
    kind: ClusterSecretStore

  target:
    name: qdrant-env-secret
    creationPolicy: Owner

  data:
    - secretKey: API_TOKEN
      remoteRef:
        key: {{ .Values.externalSecrets.secretName }}
        property: API_TOKEN

    - secretKey: AWS_ACCESS_KEY_ID
      remoteRef:
        key: {{ .Values.externalSecrets.secretName }}
        property: AWS_ACCESS_KEY_ID

    - secretKey: AWS_SECRET_ACCESS_KEY
      remoteRef:
        key: {{ .Values.externalSecrets.secretName }}
        property: AWS_SECRET_ACCESS_KEY

    - secretKey: GITLAB_TOKEN
      remoteRef:
        key: {{ .Values.externalSecrets.secretName }}
        property: GITLAB_TOKEN

    - secretKey: QDRANT_API_KEY
      remoteRef:
        key: {{ .Values.externalSecrets.secretName }}
        property: QDRANT_API_KEY