apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: qdrant-env-secret
  labels:
    app: {{ .Release.Name }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: {{ .Values.externalSecrets.secretStore }}
    kind: ClusterSecretStore

  target:
    name: qdrant-env-secret
    creationPolicy: Owner

apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: qdrant-env-secret
  labels:
    app: {{ .Release.Name }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: {{ .Values.externalSecrets.secretStore }}
    kind: ClusterSecretStore

  target:
    name: qdrant-env-secret
    creationPolicy: Owner

  dataFrom:
    {{- toYaml .Values.externalsecretEnv.dataFrom | nindent 4 }}