{{- $infraServices := index .Values "infra-services" }}
{{- $cloud := default "aws" (index $infraServices "cloud") }}
{{- $prefix := ternary (printf "%s-%s-%s" (index $infraServices "project_name") (index $infraServices "environment") (index $infraServices "region_short")) (printf "%s-%s-%s" (index $infraServices "region_short") (index $infraServices "environment") (index $infraServices "project_name")) (eq $cloud "gcp") }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: backstage-secrets
  namespace: backstage
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: {{ ternary "secretstore-gcp" "secretstore-aws" (eq $cloud "gcp") }}
    kind: ClusterSecretStore
  target:
    name: backstage-secrets
    creationPolicy: Owner
  data:
    - secretKey: AUTH_GITHUB_CLIENT_ID
      remoteRef:
        key: {{ $prefix }}-backstage-secret-github-client-id
    - secretKey: AUTH_GITHUB_CLIENT_SECRET
      remoteRef:
        key: {{ $prefix }}-backstage-secret-github-client-secret
    - secretKey: GITHUB_TOKEN
      remoteRef:
        key: {{ $prefix }}-backstage-secret-github-token
    - secretKey: GITLAB_TOKEN
      remoteRef:
        key: {{ $prefix }}-backstage-secret-gitlab-token
    - secretKey: AUTH_SECRET
      remoteRef:
        key: {{ $prefix }}-backstage-secret-auth-secret
