{{- $infraServices := index .Values "infra-services" }}
{{- $cloud := default "aws" (index $infraServices "cloud") }}
{{- $prefix := ternary (printf "%s-%s-%s" (index $infraServices "project_name") (index $infraServices "environment") (index $infraServices "region_short")) (printf "%s-%s-%s" (index $infraServices "region_short") (index $infraServices "environment") (index $infraServices "project_name")) (eq $cloud "gcp") }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: backstage-postgresql
  namespace: backstage
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: {{ ternary "secretstore-gcp" "secretstore-aws" (eq $cloud "gcp") }}
    kind: ClusterSecretStore
  target:
    name: backstage-postgresql
    creationPolicy: Owner
  data:
    - secretKey: password
      remoteRef:
        key: {{ $prefix }}-backstage-postgres-password
    - secretKey: postgres-password
      remoteRef:
        key: {{ $prefix }}-backstage-postgres-password
