apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::{{ index .Values "infra-services" "aws_account_id" }}:role/irsa-itgix-adp-{{ index .Values "infra-services" "eks_cluster_name" }}
  name: sa-itgix-adp-agent
