{{- if index .Values "infra-services" "gitlab_s3_use_irsa" }}
apiVersion: v1
kind: Secret
metadata:
  name: gitlab-object-storage
type: Opaque
stringData:
  connection: |
    provider: AWS
    region: {{ index .Values "infra-services" "region" }}
    use_iam_profile: true
{{- end }}
