apiVersion: v2
name: policy-reporter
description: A Helm chart for Kubernetes
type: application
version: 0.1.0
appVersion: "1.0"

dependencies:
- name: policy-reporter
  version: 2.24.1
  repository: https://kyverno.github.io/policy-reporter
