kyverno:
  cleanupController:
    rbac:
      clusterRole:
        extraResources:
          - apiGroups:
              - ""
            resources:
              - pods
            verbs:
              - get
              - list
              - watch
              - delete
  reportsController:
    resources:
      limits:
        memory: "256Mi"
        cpu: 600m
      requests:
        cpu: 200m
        memory: "256Mi"
  backgroundController:
    resources:
      requests:
        cpu: "50m"
        memory: "124Mi"
      limits:
        cpu: "100m"
        memory: "124Mi"
  admissionController:
    resources:
      limits:
        memory: "256Mi"
        cpu: 600m
      requests:
        cpu: 200m
        memory: "256Mi"
  configs:
    excludeKyvernoNamespace: true
    resourceFiltersExcludeNamespaces:
      - kube-system
      - external-dns