{{- if .Values.kubernetesMcp.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "aiops-platform.kubernetesMcp.clusterRoleName" . }}
  labels:
    app: kubernetes-mcp-server
rules:
  {{- toYaml .Values.kubernetesMcp.rbac.rules | nindent 2 }}
{{- end }}
