apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: aiops-agent-websocket-config
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: {{ .Values.externalSecrets.secretStoreName }}
    kind: {{ .Values.externalSecrets.secretStoreKind }}
  target:
    name: agent-websocket-security
    creationPolicy: Owner
  data:
    - secretKey: config.yaml
      remoteRef:
        key: {{ .Values.externalSecrets.websocketConfig.remoteKey | quote }}
        decodingStrategy: None
