apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: aiops-vector-secret
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: {{ .Values.externalSecrets.secretStoreName }}
    kind: {{ .Values.externalSecrets.secretStoreKind }}
  target:
    name: aiops-vector-secret
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: {{ .Values.externalSecrets.vectorSecret.remoteKey | quote }}
        metadataPolicy: None
        conversionStrategy: Default
        decodingStrategy: None
