apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: aiops-gitlab-secret
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: {{ .Values.externalSecrets.secretStoreName }}
    kind: {{ .Values.externalSecrets.secretStoreKind }}
  target:
    name: gitlab-secret
    creationPolicy: Owner
    template:
      type: kubernetes.io/dockerconfigjson
      data:
        .dockerconfigjson: '{{ "{{ .dockerconfigjson }}" }}'
  data:
    - secretKey: dockerconfigjson
      remoteRef:
        key: {{ .Values.externalSecrets.gitlabToken.remoteKey | quote }}
        decodingStrategy: None
