apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: itgix-adp-agent
  labels:
    k8s-app: itgix-adp-agent
spec:
  selector:
    matchLabels:
      name: itgix-adp-agent
  template:
    metadata:
      labels:
        name: itgix-adp-agent
    spec:
      containers:
      - name: itgix-adp-agent
        image: {{ .Values.adpagent.image }}
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
          requests:
            cpu: 10m
            memory: 50Mi
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
          successThreshold: 1
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 3
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
          successThreshold: 1
        ports:
        - containerPort: 8080
        env:
        - name: PRODUCT_CODE
          value: {{ .Values.adpagent.product_code }}
        - name: USAGEDIM
          value: {{ .Values.adpagent.usage_dimension }}
        - name: AWS_REGION
          value: {{ .Values.infra-services.usage_dimension }}
      terminationGracePeriodSeconds: 30
      serviceAccountName: sa-itgix-adp-agent
