{{- if index .Values "infra-services" "enable_fluent_bit" }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: fluent-bit
  # annotations:
  #   argocd.argoproj.io/sync-wave: "1"
  # Add this finalizer ONLY if you want these to cascade delete.
  # finalizers:
  #   - resources-finalizer.argocd.argoproj.io
spec:
  project: infra
  source:
    repoURL: {{ index .Values "infra-services" "gitops_destination_repo" }}
    targetRevision: HEAD
    path: helm/fluent-bit
    helm:
      valueFiles:
        - ../fluent-bit/values/{{ index .Values "infra-services" "environment" }}/{{ index .Values "infra-services" "region" }}/values.yaml
        - ../infra-services/values/{{ index .Values "infra-services" "environment" }}/{{ index .Values "infra-services" "region" }}/infra-facts.yaml
      values: |
        fluent-bit:
          config:
            outputs: |
              [OUTPUT]
                  Name cloudwatch_logs
                  Match *
                  region {{ index .Values "infra-services" "region" }}
                  log_group_name fluent-bit-cloudwatch
                  log_stream_prefix from-fluent-bit-
                  auto_create_group On
              [OUTPUT]
                  Name loki
                  match *
                  host loki.monitoring.svc.cluster.local
                  port 3100
                  Labels job="fluent-bit"
                  line_format json
          serviceAccount:
            create: true
            annotations:
              eks.amazonaws.com/role-arn: {{ index .Values "infra-services" "fluentbit_sa_role_arn" }}
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: fluent-bit
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  revisionHistoryLimit: 3
{{- end }}
