{{- if index .Values "infra-services" "enable_default_policies" }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: default-policies
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  # Add this finalizer ONLY if you want these to cascade delete.
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: infra
  source:
    repoURL: {{ index .Values "infra-services" "gitops_destination_repo" }}
    targetRevision: HEAD
    path: helm/kyverno-policies
    helm:
      valueFiles:
        - ../kyverno-policies/values/{{ index .Values "infra-services" "environment" }}/{{ index .Values "infra-services" "region" }}/values.yaml
        - ../infra-services/values/{{ index .Values "infra-services" "environment" }}/{{ index .Values "infra-services" "region" }}/infra-facts.yaml
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: kyverno
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - Replace=true
  revisionHistoryLimit: 3
{{- end }}
