{{- if index .Values "infra-services" "enable_barman_cloud_plugin" }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: barman-cloud-plugin
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: infra
  source:
    repoURL: {{ index .Values "infra-services" "gitops_destination_repo" }}
    targetRevision:  {{ default "HEAD" (index .Values "infra-services" "barman_cloud_plugin_branch") }}
    path: helm/barman-cloud-plugin
    helm:
      valueFiles:
        - ../barman-cloud-plugin/values/{{ index .Values "infra-services" "environment" }}/{{ index .Values "infra-services" "region" }}/values.yaml
        - ../infra-services/values/{{ index .Values "infra-services" "environment" }}/{{ index .Values "infra-services" "region" }}/infra-facts.yaml
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: cnpg-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
  revisionHistoryLimit: 3
{{- end }}
